import { SYSTEM_INSTRUCTION, CHAT_SYSTEM_INSTRUCTION } from './_lib/prompts.js';

export const PROMPTS = {
  SYSTEM_INSTRUCTIONS: SYSTEM_INSTRUCTION,
  CHAT_SYSTEM_INSTRUCTIONS: CHAT_SYSTEM_INSTRUCTION
};
